<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport"
        content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <script src="../js/error.js"></script>
  <link rel="stylesheet" href="/css/error.css">
  <title>Document</title>
</head>
<body>
<div class="not-found parallax">
  <div class="sky-bg"></div>
  <div class="wave-7"></div>
  <div class="wave-6"></div>
  <a class="wave-island" href="#">
    <img src="http://res.cloudinary.com/andrewhani/image/upload/v1524501929/404/island.svg" alt="Island">
  </a>
  <div class="wave-5"></div>
  <div class="wave-lost wrp">
    <span>5</span>
    <span>0</span>
    <span>0</span>
  </div>
  <div class="wave-4"></div>
  <div class="wave-boat">
    <img class="boat" src="http://res.cloudinary.com/andrewhani/image/upload/v1524501894/404/boat.svg" alt="Boat">
  </div>
  <div class="wave-3"></div>
  <div class="wave-2"></div>
  <div class="wave-1"></div>
  <div class="wave-message">
    <p>You're lost</p>
    <p>Some issues with server</p>
  </div>
</div>
</body>
</html>