<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="/css/home.css">
    <link rel="stylesheet" href="/css/confirmWaiting.css">
    <title>Sign Up</title>
</head>
<body>
<div class="basic" style="margin: 10% auto">
    <h1 class="success">Success!</h1>
    <form method="get" action="/">
        <button type="submit" class="submit">Sign In</button>
    </form>
</div>
</body>
</html>